= Information Dump

== Generic Introduction

A common method for extracting botnet activity is to analyze the Command and
Control (C2) server that distributes instructions to infected hosts. This
typically involves reverse-engineering the malware binary used to enroll a host
into a botnet [citation]. By understanding how a bot communicates with its C2
server, it is possible to emulate this communication and collect information
without directly participating in attacks. Applications that implement this
approach are commonly referred to as C2 miners [citation].

While effective, C2 mining through reverse-engineering does not scale easily, as
each botnet family requires significant manual effort and specialized expertise.
As a result, maintaining a comprehensive and timely overview of botnet activity
remains a largely manual and fragmented process. Addressing this limitation
requires an alternative approach to large-scale botnet intelligence gathering.

In addressing the challenge of scalable botnet intelligence gathering, this
thesis proposes _bottle_, an approach that observes the behavior of botnet
malware in a controlled environment rather than relying on detailed
reverse-engineering of individual botnet implementations. At a high level, the
idea is to allow malware to communicate with its command infrastructure while
preventing harm. By executing malware without modification, this approach
reduces the amount of manual, botnet-specific effort required to extract
intelligence from newly emerging malware families.

This shift from botnet-specific reverse-engineering to behavioral monitoring
aims to enable the scalable collection of technical intelligence about active
botnets and their operational characteristics, while remaining agnostic to
individual malware implementations.

== Technical Description

The aim of this project project was to determine whether allowing samples
communication with their C2 server, but restrict other in/outbound
communications, would still result in attacks that can be monitored for extended
periods of time. Effectively, our method proposes using sandboxes and simple
network monitoring as C2 miners, eliminating the need of reverse-engineering.

=== Technique

All samples are ran in 'simple' sandboxes, QEMU VMs running Debian, which do not
have internet access, save the C2 server if it's known at that point in time and
rate-limited access to Cloudflare and Google DNS. All non-c2 traffic is routed
to _inetsim_ to ensure the malware assumes an active internet connection, and as
a generic measure against possible sandbox evasion techniques.

Concretely, the proposed approach works on a two-stage basis:

1. *Determine potential C2 addresses of a sample*: By running the sample in a
  basic sandbox with minimal (rate-limited) DNS access, the hope is that the
  malware will display network activity to its C2 server. All IP addresses that
  do are not concerned with DNS or NTP are considered possible C2 server
  candidites.

2. *Allow communications with potential C2 server*: Now, the bot is allowed to
  communicate with a _potential_ C2 server. At this point in time, this address
  can (1) correspond to a c2 server that is actively attacking, (2) point to a
  c2 server that is not actively attacking, (3) not belong to a C2 server at
  all.

=== Pipeline

The `bottle` pipeline we've developed is, in effect, a stack made up of the following applications and tools:

- The `bottle` orchestrator

#quote([
  bottle is the orchestration and monitoring layer that sits on top of a
  bottled deployment. It keeps a ledger of analyses, submits runs to the bottle
  daemon, watches Suricata logs for C2 activity, and optionally ingests new
  samples from MalwareBazaar. Use it when you need to keep long-running sandboxes
  alive, automatically requeue samples, and collect forensic data without
  babysitting the bottle daemon.
])

- The `bottle` daemon (`bottled`)

#quote([
  bottled is a Go toolkit for building long-lived sandbox images and repeatedly
  running botnet or malware samples inside them. It wraps libvirt, nftables, and a
  curated set of Debian-based VM specifications so you can build images, lease
  them for sandbox runs, launch analyses, or hand those runs off to a
  daemon for continuous monitoring.
])

- The `bottle` monitor (`botmon`)

#quote([
  gomon detects interesting network activity generated by sandboxed bots or
  malware samples. It ingests live interfaces or PCAP captures, groups traffic
  into sliding windows, and emits Suricata-compatible alerts whenever
  packet-rate or destination-diversity thresholds are exceeded. The tool pairs
  well with bottle, but it can also run standalone on any host with libpcap.
])

These results are pushed into clickhouse, the results of which are aggregated
into grafana, which allows us to have a real-time overview of C2 servers and
targets.

=== Network Monitoring

To determine whether a sample is performing an attack, is scanning, or is
establishing a 'regular' outbound connection, we employ simple thresholds on
two metrics across a timewindow:

1. The packet rate per _destination_, where destinations are ip/port
  combinations. The packet rate is calculated as the number of packets in a time
  window, normalized by the size of the window in seconds.

2. The _new destination rate_, which is calculated by taking the number of
  unique destinations that did not appear in the previous time window. This
  is again normalized by the size of the window.

The last metric was introduced to allow for distinguishing between scanning and
the DoSing of multiple hosts at the same time. In a scanning regime, new
destinations are constantly probed, while we assume that attacks generally do
not introduce new targets as quickly as scanning.

The success of this approach depends significantly on the discrepancy between
the rate of new destinations in either regime when using simple thresholding,
and of course the size of the window.

Seeing as many malware samples are capable of scanning autonomously, being able
to distinguish between scans and attacks allows us to determine botnet activity
with higher confidence, since attacks (in our observations) are never initiated
by bots independently.

In addition to increasing confidence in activity, we can now take snapshots of
attacks to investigate later and confirm this suspicion. Having raw attack
snapshots of arbitraty length could be of use for defenders in improving DDoS
detection and mitigation by having a large volume of various data that reflect
real-world attacking behavior.
